Allow editing of newly added join features
opengisch/qgis-linking-relation-editor pull request #42
Opened 2023-05-02 14:02 UTC by domi4484

2023-05-04 08:16 UTC, signedav commented
Another thing: The debug warnings, should they be enabled all the time?
E.g.
```
        if Debug:
            QgsMessageLog.logMessage("parentFormValueChanged()")
```

2023-05-04 08:21 UTC, signedav requested changes

2023-05-04 12:00 UTC, domi4484 commented
> Another thing: The debug warnings, should they be enabled all the time? E.g.
> 
> ```
>         if Debug:
>             QgsMessageLog.logMessage("parentFormValueChanged()")
> ```

Mmm probably I copied this line from the plugin I used as a template and I don't know what is the point about this log.

More in general, I think that warning should always be traced. Otherwise when there is a problem difficult to reproduce we could miss useful information.

2023-05-04 12:17 UTC, domi4484 commented on linking_relation_editor/gui/linking_relation_editor_widget.py
> +        else:
This signal was introduced in qgis 3.24 to let the attrbute form know that some children features where added/removed and accordingly updated default value fields depending on them, see [qgis pr](https://github.com/qgis/QGIS/pull/46167)

2023-05-04 12:18 UTC, signedav commented on linking_relation_editor/gui/linking_relation_editor_widget.py
> +        else:
I mean the else doing nothing.

2023-05-04 12:30 UTC, domi4484 commented on linking_relation_editor/gui/linking_relation_editor_widget.py
> +        else:
In the else the join feature are created, if not already created by the dialog (the normal if case).
This implementation is not very nice because, in one case the link is done in the dialog, and in another case is it done here.. Maybe be fixing the error that you discovered by testing I will find a cleaner way.

2023-06-16 06:22 UTC, domi4484 commented
I finally finished the transition from QTreeWidget to QTreeView. @signedav can you give it a try again?

2023-06-16 11:42 UTC, signedav approved these changes
Looks good. I tested successfully.

2023-06-16 12:25 UTC, merged