Print a warning when the relations are invalid
opengisch/qgis-linking-relation-editor pull request #51
Opened 2024-10-05 20:16 UTC by domi4484

This can happen if a relation is deleted after the widget was added to a layer configuration.

With this changes the issue persists but it logs a warning instead of throwing a python exception when trying to access referencedLayer()

2024-10-05 20:54 UTC, domi4484 commented
Still this can sometimes be quite difficult for a user to notice... Im not sure how we could improve the situation

2024-10-07 07:20 UTC, signedav requested changes

2024-10-07 07:20 UTC, signedav commented on linking_relation_editor/gui/linking_relation_editor_widget.py
> +            self._checkTransactionGroup()
Does it only need to checktransactiongroup on relation and not on nm relation?

I wonder generally if you could maybe do: 
```
if not relation.isvalid and not nmrelation.isvalid:
  warnign and return
  
 checkTranslation group
 and other stuff
 ```

2024-10-07 07:23 UTC, signedav commented
> Im not sure how we could improve the situation

How is it solved on normal relation editor? On a quick test it seems that it's just ignored: 
![Uploading image.png…]()

2024-10-07 09:49 UTC, domi4484 commented on linking_relation_editor/gui/linking_relation_editor_widget.py
> +            self._checkTransactionGroup()
You are right, it doesn't make many sense to continue if `relation` is not valid. And I think we can't have any case were `nmRelation` is valid but not `relation`
Still we need to call self.updateButtons before return

2024-10-07 10:18 UTC, domi4484 commented
@signedav thanks for the review. Yes it QGIS it is just ignored. It would be good to add something visual like a warning logo or something like that in the layer properties.
For normal fields is the same, if you add a field per drag&drop, and remove it from the layer the widget remains in the configuration.

2024-12-02 10:01 UTC, domi4484 commented
@signedav can I merge this?

In future there will be as well some indicator in QGIS but having the warning in the logs can still be very useful: https://github.com/qgis/QGIS/pull/59654

2024-12-02 10:20 UTC, signedav commented
yes, thanks

2024-12-02 19:29 UTC, merged